categorical_cols:
  - BusinessTravel
  - Department
  - EducationField
  - Gender
  - JobRole
  - MaritalStatus
  - Over18
  - OverTime
ohe_encoder_path: /data/ohe_encoder.joblib
target_encoder_path: /data/target_encoder.joblib
target_col: Attrition
model_name: random_forest
experiment_name: random_forest_training
run_name: V1