FROM python:3.8-slim-buster

# Set working directory
WORKDIR /

COPY inference_pipeline/requirements.txt .
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y git

COPY inference_pipeline/entrypoint.sh .
RUN chmod +x /entrypoint.sh

EXPOSE 8080

# Run training pipeline
ENTRYPOINT ["/entrypoint.sh"]
