version: '3'
services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.train.feature
    image: attrition_train_image
    container_name: attrition_train
    ports:
      - '5000:5000'
    volumes:
      - ${PWD}/train_pipeline:/train_pipeline
      - ${PWD}/data:/data
      - ${PWD}/mlflow_runs:/mlflow_runs
    environment:
      CONFIG_FILE: config_dev.yaml