version: '3'
services:
  infer:
    build:
      context: .
      dockerfile: Dockerfile.infer
    image: attrition_infer_image:stage
    container_name: attrition_infer_${BRANCH_TAG}
    ports:
      - '8080:8080'
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/mlflow_runs:/mlflow_runs
    environment:
      CONFIG_FILE: ${CONFIG_FILE}
      BRANCH_TAG: ${BRANCH_TAG}
